### ISSUE TITLE
IntDelaunayTriangulation overflow

### ISSUE THREAD

**Issue by purpleposeidon** [Stoeoef/spade#53]
```rust
#[test]
fn overflows() {
    use spade::delaunay::*;
    let mut tris = IntDelaunayTriangulation::with_walk_locate();
    for &p in &[
        [-100, -100],
        [0, 0],
        [-200, -100],
        [200, -100],
    ] {
        tris.insert(p);
    }
}
```

```
thread 'main' panicked at 'attempt to multiply with overflow', /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/ops/arith.rs:318:45
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::panicking::panic
             at src/libcore/panicking.rs:70
  15: <i32 as core::ops::arith::Mul>::mul
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/ops/arith.rs:318
  16: spade::kernels::DelaunayKernel::contained_in_circumference
             at /home/poseidon/.cargo/registry/src/github.com-1ecc6299db9ec823/spade-1.8.1/src/kernels.rs:60
  17: spade::delaunay::delaunay_basic::BasicDelaunaySubdivision::legalize_edges
             at /home/poseidon/.cargo/registry/src/github.com-1ecc6299db9ec823/spade-1.8.1/src/delaunay/delaunay_basic.rs:573
  18: spade::delaunay::delaunay_basic::BasicDelaunaySubdivision::insert_outside_convex_hull
             at /home/poseidon/.cargo/registry/src/github.com-1ecc6299db9ec823/spade-1.8.1/src/delaunay/delaunay_basic.rs:427
  19: spade::delaunay::delaunay_basic::BasicDelaunaySubdivision::insert_with_hint_option
             at /home/poseidon/.cargo/registry/src/github.com-1ecc6299db9ec823/spade-1.8.1/src/delaunay/delaunay_basic.rs:272
  20: spade::delaunay::delaunay2d::DelaunayTriangulation<V,K,L>::insert
             at /home/poseidon/.cargo/registry/src/github.com-1ecc6299db9ec823/spade-1.8.1/src/delaunay/delaunay2d.rs:449
  21: playground::main
             at src/main.rs:88
```

**Comment by Stoeoef** [comment]
Thanks for reporting this!

The overflow issues with `IntDelaunayTriangulation` [are actually a known issue](https://docs.rs/spade/1.8.1/spade/kernels/enum.TrivialKernel.html). Admittedly, I'm surprised to see it happen at these low value ranges.

Some workarounds:
 - Use a [FloatDelaunayTriangulation](https://docs.rs/spade/1.8.1/spade/delaunay/type.FloatDelaunayTriangulation.html), even for integral types
 - Using `i64` instead of `i32` - this already is enough to prevent the overflow in your example.
 - Use an [AdaptiveIntKernel](https://docs.rs/spade/1.8.1/spade/kernels/enum.AdaptiveIntKernel.html) if you *really* want to continue to use integers. It's slower than floats, unfortunately.

For the second option, change L17 to this:
```rust
[-100i64, -100],
```
Rust defaults to `i32` if no specific integer type is given.

Just as a heads up: The support for integral types has not lived up to my hopes and will be removed in future versions (>= 2.0)

Let me know if you have any follow up questions or problems!

**Comment by Stoeoef** [comment]
Support of integer types has been removed as part of Spade 2.0, rendering this issue obsolete. Closing!
